### ISSUE TITLE
no implicit conversion of String into Integer

### ISSUE THREAD

**Issue by lluchs** [ckanibal/crema#2]
I'm getting the following error:

```
2019-08-31 23:49:00.962218500 Unexpected error while processing request: no implicit conversion of String into Integer
2019-08-31 23:49:00.962220500   /home/clnk/deploy/crema/server.rb:66:in `[]'
2019-08-31 23:49:00.962221500   /home/clnk/deploy/crema/server.rb:66:in `block (5 levels) in <top (required)>'
2019-08-31 23:49:00.962272500   /home/clnk/deploy/crema/server.rb:65:in `each'
2019-08-31 23:49:00.962273500   /home/clnk/deploy/crema/server.rb:65:in `block (4 levels) in <top (required)>'
2019-08-31 23:49:00.962274500   /package/host/localhost/ruby-2.5.6/lib/ruby/2.5.0/open-uri.rb:169:in `open_uri'
2019-08-31 23:49:00.962275500   /package/host/localhost/ruby-2.5.6/lib/ruby/2.5.0/open-uri.rb:735:in `open'
2019-08-31 23:49:00.962276500   /package/host/localhost/ruby-2.5.6/lib/ruby/2.5.0/open-uri.rb:35:in `open'
2019-08-31 23:49:00.962282500   /home/clnk/deploy/crema/server.rb:61:in `block (3 levels) in <top (required)>'
```

```
% ruby --version
ruby 2.5.6p201 (2019-08-28 revision 67796) [x86_64-linux]
```

**Comment by Somebodyisnobody** [comment]
Hey, I just wanted to make sure the issue didn't fall into oblivion. Is there any progress?
